import Foundation

/// One distinct value found in a merged column, with how many rows carry it
/// and the source files it appears in (by file name, sorted).
struct DistinctValue: Identifiable {
    // Unique per (value, source files) so same-value/different-file rows
    // stay distinct in lists (동명이인은 별도 행). When `uid` is set (raw row
    // mode), it makes each source row unique even if value+file repeat.
    var id: String {
        if !uid.isEmpty { return uid }
        return files.isEmpty ? value : value + "\u{1}" + files.joined(separator: ",")
    }
    let value: String
    let count: Int
    var files: [String] = []
    // Row identifiers that carried this value (Code → Email → 행 N), so a value
    // seen here can be traced back to its row in the original file. Detail view only.
    var refs: [String] = []
    // Set in raw (un-grouped) row mode to keep every source row distinct.
    var uid: String = ""
}

/// Discovers which merged columns hold categorical values worth unifying
/// (e.g. a 도시 column where some rows say "Seoul" and others "서울"),
/// and the distinct values that land in each across all files.
enum ValueScanner {

    /// Free-text or derived columns — never offered for value unification.
    static let freeText: Set<UnifiedColumn> = [
        .koreanName, .email, .phone, .phoneClean, .dob, .dobClean, .code, .channel, .dupFlag,
        .currentAddress, .selfIntro, .motivation, .essayInitiative, .essayCraft, .essayChallenge,
        .portfolioLinks, .portfolioFile, .cvFile, .coreCompetencies, .submittedAt,
        .major, .school, .schoolCompany, .majorDept, .snsChannel,
        // 메타/후속/파생 컬럼 — 값 통일 대상 아님
        .onTestScore, .fifthApply, .foundationOrigin, .scoreFrom, .onTestPass, .eventApplicant,
        .regCohort, .regBatch, .regAcademy, .curCohort, .curBatch, .totalActiveChoices,
        .confirmedAt, .blocked, .disabled, .registeredAt, .lastLogin, .deleted,
        .tncAge, .tncContact, .academyChoice, .age, .ageGroup, .idDocType, .idNumber,
        .cityOverseas, .postalCode, .placeOfBirth, .dualMajor, .uniStats, .othersSpecify,
        .accomodation, .sessionPref, .motivVideo, .linkedin
    ]

    /// A column with more distinct values than this is treated as free-text, not categorical.
    static let maxDistinct = 40

    /// Distinct non-empty values for a column across all files, most frequent first.
    static func distinct(_ col: UnifiedColumn, in plans: [FilePlan]) -> [DistinctValue] {
        var counts: [String: Int] = [:]
        var files: [String: Set<String>] = [:]
        for plan in plans where plan.isMapped(col) {
            for row in plan.rows {
                let v = plan.compose(col, from: row)
                if v.isEmpty { continue }
                counts[v, default: 0] += 1
                files[v, default: []].insert(plan.fileName)
            }
        }
        return counts
            .sorted { $0.value != $1.value ? $0.value > $1.value : $0.key < $1.key }
            .map { DistinctValue(value: $0.key, count: $0.value, files: (files[$0.key] ?? []).sorted()) }
    }

    /// Columns worth a value-unification pass: mapped somewhere, categorical, low-cardinality.
    static func candidates(in plans: [FilePlan]) -> [UnifiedColumn] {
        UnifiedColumn.allCases.filter { col in
            guard !freeText.contains(col) else { return false }
            guard plans.contains(where: { $0.isMapped(col) }) else { return false }
            let n = distinct(col, in: plans).count
            return n >= 2 && n <= maxDistinct
        }
    }
}

// MARK: - Column-centric review

/// How a final column should be reviewed.
/// - category: distinct values to unify
/// - phone/date: auto-normalized, shown as original → cleaned samples
/// - freeText: kept as-is, shown as a few sample values
/// - derived: generated by the merge (channel, dup flag, *(Clean) columns)
enum ColumnReviewKind { case category, phone, date, freeText, derived }

/// 사용자가 컬럼에 직접 지정하는 검토 타입. 자동 판단이 기본값이지만, 언제든
/// 셋 중 하나로 바꿀 수 있다 (파생 컬럼 제외).
/// - freeText: 사용자가 적은 값 — 그대로 두되 오타 의심값만 알려준다.
/// - category: 정해둔 선택지(허용 목록)만 허용 — 벗어난 값은 결정 대상.
/// - format:   정해둔 형식(전화번호/이메일/생년월일/직접 정규식)에 맞춰야 한다.
enum ColumnType: String, CaseIterable, Identifiable {
    case freeText = "자유 입력"
    case category = "범주"
    case format   = "포맷"
    var id: String { rawValue }
    var symbol: String {
        switch self {
        case .freeText: return "text.alignleft"
        case .category: return "checklist"
        case .format:   return "textformat.123"
        }
    }
    var help: String {
        switch self {
        case .freeText: return "사용자가 적은 값 그대로 둡니다. 오타 같아 보이는 값만 알려줘요."
        case .category: return "정해둔 선택지만 허용합니다. 목록을 벗어난 값은 결정 대상으로 표시돼요."
        case .format:   return "정해둔 형식(전화번호·이메일·생년월일·직접 정규식)에 맞춰야 합니다."
        }
    }
}

/// 포맷 타입 컬럼이 맞춰야 할 형식. custom은 사용자가 직접 정규식을 입력한다.
enum FormatPreset: String, CaseIterable, Identifiable {
    case phone  = "전화번호"
    case email  = "이메일"
    case date   = "생년월일"
    case custom = "직접 입력"
    var id: String { rawValue }
    /// 값 전체가 이 정규식에 맞아야 통과 (custom은 사용자 입력을 별도로 씀).
    var pattern: String {
        switch self {
        case .phone:  return "\\d{2,3}-\\d{3,4}-\\d{4}"
        case .email:  return "[^@\\s]+@[^@\\s]+\\.[^@\\s]+"
        case .date:   return "\\d{4}-\\d{2}-\\d{2}"
        case .custom: return ""
        }
    }
    var hint: String {
        switch self {
        case .phone:  return "010-XXXX-XXXX"
        case .email:  return "x@y.z"
        case .date:   return "yyyy-MM-dd"
        case .custom: return "정규식 직접 입력"
        }
    }
}

/// One explicit conversion proposal for a normalized column (phone/date):
/// 이전 값과 제안 값을 모두 보여주고, 사용자가 승인(이대로 OK)해야 적용됩니다.
struct ProposedChange: Identifiable {
    var id: String { value }
    let value: String          // 이전 값 (원본)
    let count: Int             // 이 값이 나온 행 수
    let proposed: String       // 제안 값 (병합 시 Clean 컬럼에 적용)
    let standard: Bool         // 제안이 목표 형식에 도달했는가
    var changed: Bool { proposed != value }
}

/// What to review for a single final output column.
struct ColumnReview: Identifiable {
    var id: String { column.rawValue }
    let column: UnifiedColumn
    let kind: ColumnReviewKind
    var values: [DistinctValue] = []     // categorical: distinct values to unify
    var samples: [String] = []           // freeText: a few sample values
    var anomalies: [AnomalyDetector.Finding] = []  // freeText: values that look off
    var flaggedValues: [DistinctValue] = []  // phone/date: every value the normalizer couldn't standardize
    var proposals: [ProposedChange] = []     // phone/date: every distinct value with its proposed conversion
    var note: String = ""                // derived/freeText: short description
    var flaggedCount: Int = 0            // phone/date: rows needing attention
    var distinctCount: Int = 0
    var total: Int = 0                   // rows carrying a value
}

/// Builds the column-centric review: which columns the merge will produce,
/// and, per column, the values or formats the user should look over.
enum ColumnReviewBuilder {

    static func mappedSomewhere(_ col: UnifiedColumn, in plans: [FilePlan]) -> Bool {
        plans.contains { $0.isMapped(col) }
    }

    /// Every non-empty composed value of a column across all files.
    static func rawValues(_ col: UnifiedColumn, in plans: [FilePlan]) -> [String] {
        var out: [String] = []
        for plan in plans where plan.isMapped(col) {
            for row in plan.rows {
                let v = plan.compose(col, from: row)
                if !v.isEmpty { out.append(v) }
            }
        }
        return out
    }

    /// Columns that will appear in the merged file, in export order.
    static func finalColumns(in plans: [FilePlan]) -> [UnifiedColumn] {
        UnifiedColumn.allCases.filter { col in
            switch col {
            case .channel, .dupFlag, .code: return true   // code: 간편지원은 생성됨
            case .phoneClean: return mappedSomewhere(.phone, in: plans)
            case .dobClean:   return mappedSomewhere(.dob, in: plans)
            case .age, .ageGroup: return mappedSomewhere(.dob, in: plans)
            default:          return mappedSomewhere(col, in: plans)
            }
        }
    }

    private static let isoDate = "^\\d{4}-\\d{2}-\\d{2}$"

    /// One review per final column, in export order.
    static func reviews(in plans: [FilePlan]) -> [ColumnReview] {
        let categorical = Set(ValueScanner.candidates(in: plans))
        let rowTotal = plans.reduce(0) { $0 + $1.rows.count }

        return finalColumns(in: plans).map { col in
            switch col {
            case .channel:
                return ColumnReview(column: col, kind: .derived,
                                    note: "각 행이 어느 파일(간편지원/일반지원)에서 왔는지 자동으로 채워집니다.",
                                    total: rowTotal)
            case .dupFlag:
                return ColumnReview(column: col, kind: .derived,
                                    note: "전화번호 기준 중복 검사 결과(유지/삭제)가 자동으로 채워집니다.",
                                    total: rowTotal)
            case .phoneClean:
                return ColumnReview(column: col, kind: .derived,
                                    note: "‘Phone Number’에서 ‘010-XXXX-XXXX’ 형태로 자동 생성됩니다.")
            case .dobClean:
                return ColumnReview(column: col, kind: .derived,
                                    note: "‘Date of Birth’에서 ‘yyyy-MM-dd’ 형태로 자동 생성됩니다.")
            case .age:
                return ColumnReview(column: col, kind: .derived,
                                    note: "아카데미 시작일(다음 3월 1일) 기준 만 나이가 ‘생년월일(Clean)’에서 계산됩니다.")
            case .ageGroup:
                return ColumnReview(column: col, kind: .derived,
                                    note: "만 나이를 19-20 / 21-25 / … / 41+ 구간으로 묶습니다. 생일 미인식은 NA.")
            case .code:
                return ColumnReview(column: col, kind: .derived,
                                    note: "일반지원은 원본 Code 유지, Code가 없는 간편지원에는 ‘6F10001’부터 일련번호가 자동 부여됩니다.")
            case .phone:
                let raw = rawValues(.phone, in: plans)
                let distinct = ValueScanner.distinct(.phone, in: plans)
                // 모든 종을 명시적 제안으로: 이전 값 → 제안 값 (숨기는 변환 없음)
                let proposals = distinct.map { dv -> ProposedChange in
                    let cleaned = Normalizer.cleanPhone(dv.value)
                    return ProposedChange(value: dv.value, count: dv.count,
                                          proposed: cleaned, standard: cleaned.hasPrefix("010-"))
                }
                let flaggedValues = distinct.filter { !Normalizer.cleanPhone($0.value).hasPrefix("010-") }
                return ColumnReview(column: col, kind: .phone,
                                    values: distinct,       // 타입을 바꿔도 쓰도록 값 목록 보존
                                    flaggedValues: flaggedValues,
                                    proposals: proposals,
                                    note: "원본은 그대로 저장되고, 제안 값이 ‘전화번호(Clean)’ 컬럼에 들어갑니다. 아래 표가 변환의 전부입니다.",
                                    flaggedCount: flaggedValues.count,
                                    distinctCount: Set(raw).count, total: raw.count)
            case .dob:
                let raw = rawValues(.dob, in: plans)
                let distinct = ValueScanner.distinct(.dob, in: plans)
                let proposals = distinct.map { dv -> ProposedChange in
                    let cleaned = Normalizer.cleanDate(dv.value)
                    let ok = cleaned.range(of: isoDate, options: .regularExpression) != nil
                    return ProposedChange(value: dv.value, count: dv.count,
                                          proposed: cleaned, standard: ok)
                }
                let flaggedValues = distinct.filter {
                    Normalizer.cleanDate($0.value) == $0.value
                        && $0.value.range(of: isoDate, options: .regularExpression) == nil
                }
                return ColumnReview(column: col, kind: .date,
                                    values: distinct,       // 타입을 바꿔도 쓰도록 값 목록 보존
                                    flaggedValues: flaggedValues,
                                    proposals: proposals,
                                    note: "원본은 그대로 저장되고, 제안 값이 ‘생년월일(Clean)’ 컬럼에 들어갑니다. 아래 표가 변환의 전부입니다.",
                                    flaggedCount: flaggedValues.count,
                                    distinctCount: Set(raw).count, total: raw.count)
            default:
                // 사용자가 타입(자유입력/범주/포맷)을 언제든 바꿀 수 있도록, 비파생
                // 컬럼은 값 목록·샘플·오타 후보를 모두 채워 둔다. 자동 판단 기본값만
                // kind로 표시하고, 실제 렌더링/검증은 사용자가 고른 타입을 따른다.
                let d = ValueScanner.distinct(col, in: plans)
                let isCat = categorical.contains(col)
                return ColumnReview(column: col,
                                    kind: isCat ? .category : .freeText,
                                    values: d,
                                    samples: d.prefix(5).map { $0.value },
                                    anomalies: AnomalyDetector.scan(d),
                                    note: isCat ? "정해둔 선택지로 값을 통일합니다."
                                                : "자유 입력 값이라 통일 없이 원본 그대로 저장됩니다.",
                                    distinctCount: d.count,
                                    total: d.reduce(0) { $0 + $1.count })
            }
        }
    }

    /// Every value (with counts) for any final column — including derived ones —
    /// for the detail viewer. Rows are split **per source file**: the same value
    /// coming from two files becomes two rows, so 동명이인(같은 값·다른 출처)이
    ///하나로 합쳐지지 않습니다. Most frequent first.
    static func allValues(_ col: UnifiedColumn, in plans: [FilePlan],
                          phoneTemplate: String = Normalizer.defaultPhoneTemplate) -> [DistinctValue] {
        switch col {
        case .channel:
            // One row per file (its channel label), so same-channel files stay separate.
            return flatten(plans.reduce(into: [:]) { acc, plan in
                acc[plan.channel.rawValue, default: [:]][plan.fileName, default: 0] += plan.rows.count
            })
        case .dupFlag:
            return []   // decided during the merge
        case .phoneClean:
            return perFile(.phone, in: plans, clean: {
                Normalizer.formatPhone($0, template: phoneTemplate)
                    ?? $0.trimmingCharacters(in: .whitespacesAndNewlines)
            })
        case .dobClean:
            return perFile(.dob, in: plans, clean: Normalizer.cleanDate)
        case .age:
            return perFile(.dob, in: plans,
                           clean: { Normalizer.age(fromCleanDob: Normalizer.cleanDate($0)) })
        case .ageGroup:
            return perFile(.dob, in: plans, clean: {
                Normalizer.ageGroup(fromAge: Normalizer.age(fromCleanDob: Normalizer.cleanDate($0)))
            })
        default:
            return perFile(col, in: plans, clean: { $0 })
        }
    }

    /// One row per **source row** (nothing grouped) for the "원본 행 펼치기" view:
    /// every row keeps its own value and 출처 키, so duplicates are visible as
    /// separate lines instead of being collapsed into "외 N".
    static func rawRows(_ col: UnifiedColumn, in plans: [FilePlan],
                        phoneTemplate: String = Normalizer.defaultPhoneTemplate) -> [DistinctValue] {
        var out: [DistinctValue] = []
        for plan in plans {
            for (i, row) in plan.rows.enumerated() {
                let v = rowValue(col, plan, row, phoneTemplate)
                if v.isEmpty { continue }
                out.append(DistinctValue(value: v, count: 1, files: [plan.fileName],
                                         refs: [plan.rowRef(row, index: i)],
                                         uid: "\(plan.fileName)\u{1}\(i)"))
            }
        }
        return out
    }

    /// The value this column shows for a single source row, mirroring `allValues`
    /// (derived columns are computed, not read).
    private static func rowValue(_ col: UnifiedColumn, _ plan: FilePlan,
                                 _ row: [String: String],
                                 _ phoneTemplate: String = Normalizer.defaultPhoneTemplate) -> String {
        switch col {
        case .channel:    return plan.applicationType
        case .dupFlag:    return ""
        case .phoneClean:
            let raw = plan.compose(.phone, from: row)
            return Normalizer.formatPhone(raw, template: phoneTemplate)
                ?? raw.trimmingCharacters(in: .whitespacesAndNewlines)
        case .dobClean:   return Normalizer.cleanDate(plan.compose(.dob, from: row))
        case .age:
            return Normalizer.age(fromCleanDob: Normalizer.cleanDate(plan.compose(.dob, from: row)))
        case .ageGroup:
            return Normalizer.ageGroup(fromAge:
                Normalizer.age(fromCleanDob: Normalizer.cleanDate(plan.compose(.dob, from: row))))
        default:          return plan.compose(col, from: row)
        }
    }

    /// value -> file -> count, composing (and optionally cleaning) each row.
    /// Also gathers a traceable row identifier per occurrence (refs).
    private static func perFile(_ col: UnifiedColumn, in plans: [FilePlan],
                                clean: (String) -> String) -> [DistinctValue] {
        var counts: [String: [String: Int]] = [:]
        var refs: [String: [String: [String]]] = [:]
        for plan in plans where plan.isMapped(col) {
            for (i, row) in plan.rows.enumerated() {
                let v = plan.compose(col, from: row)
                if v.isEmpty { continue }
                let c = clean(v)
                if c.isEmpty { continue }
                counts[c, default: [:]][plan.fileName, default: 0] += 1
                refs[c, default: [:]][plan.fileName, default: []].append(plan.rowRef(row, index: i))
            }
        }
        return flatten(counts, refs)
    }

    /// Expand a value→file→count map into one row per (value, file),
    /// attaching the gathered row identifiers (deduped, capped).
    private static func flatten(_ counts: [String: [String: Int]],
                                _ refs: [String: [String: [String]]] = [:]) -> [DistinctValue] {
        var out: [DistinctValue] = []
        for (value, perFile) in counts {
            for (file, n) in perFile {
                var seen = Set<String>()
                var r = (refs[value]?[file] ?? []).filter { seen.insert($0).inserted }
                if r.count > 50 { r = Array(r.prefix(50)) }
                out.append(DistinctValue(value: value, count: n, files: [file], refs: r))
            }
        }
        return out.sorted {
            if $0.count != $1.count { return $0.count > $1.count }
            if $0.value != $1.value { return $0.value > $1.value }
            return ($0.files.first ?? "") < ($1.files.first ?? "")
        }
    }

}

// MARK: - Anomaly detection

/// Flags values that deviate from a short, identifier-like column's typical
/// shape — a name written "김-지호", stray/edge spaces, digits mixed into a
/// Korean value, 한·영 혼용 — and proposes a cleanup the user can apply or edit.
///
/// Tuned for short Korean fields (이름·도시 등). Long-form text (essays,
/// addresses, links) is left alone: those would drown in false positives.
enum AnomalyDetector {

    /// One flagged value: why it looks off, and a suggested cleanup.
    struct Finding: Identifiable {
        var id: String { value }
        let value: String
        let count: Int
        let reason: String
        let suggestion: String     // proposed cleanup; "" means flag-only (no safe auto-fix)
        let files: [String]
        var fixable: Bool { !suggestion.isEmpty && suggestion != value }
    }

    /// Columns whose median value is longer than this are skipped (free-form text).
    static let maxMedianLength = 16

    /// Characters that shouldn't sit between Korean syllables in a name/short value.
    private static let separators = CharacterSet(charactersIn: "-_/·ㆍ.,|\\~")
    private static let openBrackets = CharacterSet(charactersIn: "([{（【")

    /// Findings for a column's distinct values, most frequent first.
    static func scan(_ values: [DistinctValue]) -> [Finding] {
        let nonEmpty = values.filter { !$0.value.isEmpty }
        guard !nonEmpty.isEmpty else { return [] }
        let lengths = nonEmpty.map { $0.value.count }.sorted()
        let median = lengths[lengths.count / 2]
        guard median <= maxMedianLength else { return [] }

        var out: [Finding] = []
        for dv in nonEmpty {
            guard let (reason, suggestion) = classify(dv.value, median: median) else { continue }
            out.append(Finding(value: dv.value, count: dv.count,
                               reason: reason, suggestion: suggestion, files: dv.files))
        }
        return out.sorted { $0.count != $1.count ? $0.count > $1.count : $0.value < $1.value }
    }

    /// First matching rule wins. A "" suggestion means "flag only, no safe fix".
    private static func classify(_ v: String, median: Int) -> (reason: String, suggestion: String)? {
        // 1) leading/trailing or doubled-up whitespace
        let collapsed = collapseWhitespace(v)
        if collapsed != v {
            return ("앞뒤·연속 공백이 있습니다", collapsed)
        }
        let hangul = hasHangul(v)
        // 2) parenthetical 병기 in a Korean value, e.g. "김지호(Kim)"
        if hangul, v.rangeOfCharacter(from: openBrackets) != nil {
            let stripped = collapseWhitespace(stripParenthetical(v))
            return ("괄호 안 병기가 포함돼 있습니다", stripped == v ? "" : stripped)
        }
        // 3) separator wedged between Korean syllables, e.g. "김-지호"
        if hangul, v.rangeOfCharacter(from: separators) != nil {
            let joined = collapseWhitespace(removeSeparators(v))
            return ("값 사이에 구분 기호(\(firstSeparator(v)))가 있습니다", joined.isEmpty ? "" : joined)
        }
        // 4) digits mixed into a Korean value, e.g. "김지호1"
        if hangul, v.contains(where: { $0.isNumber }) {
            return ("숫자가 섞여 있습니다", "")
        }
        // 5) 한글·영문 혼용, e.g. "김Jiho"
        if hangul, hasLatin(v) {
            return ("한글과 영문이 섞여 있습니다", "")
        }
        // 6) unusually long for a very short field (e.g. two names run together)
        if median <= 6, v.count >= 8, v.count > median * 3 {
            return ("다른 값보다 유난히 깁니다", "")
        }
        return nil
    }

    // MARK: character classes

    private static func hasHangul(_ s: String) -> Bool {
        s.unicodeScalars.contains {
            (0xAC00...0xD7A3).contains($0.value)   // 가-힣
                || (0x1100...0x11FF).contains($0.value)   // Jamo
                || (0x3130...0x318F).contains($0.value)   // compatibility Jamo
        }
    }
    private static func hasLatin(_ s: String) -> Bool {
        s.contains { $0.isLetter && $0.isASCII }
    }

    // MARK: cleanups

    private static func collapseWhitespace(_ s: String) -> String {
        s.components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
    }
    private static func removeSeparators(_ s: String) -> String {
        String(String.UnicodeScalarView(s.unicodeScalars.filter { !separators.contains($0) }))
    }
    private static func stripParenthetical(_ s: String) -> String {
        let pattern = "\\s*[\\(\\[\\{（【][^\\)\\]\\}）】]*[\\)\\]\\}）】]"
        return s.replacingOccurrences(of: pattern, with: "", options: .regularExpression)
    }
    private static func firstSeparator(_ s: String) -> String {
        for ch in s where String(ch).rangeOfCharacter(from: separators) != nil { return String(ch) }
        return ""
    }
}

/// Suggests how to collapse value variants onto one canonical form.
enum ValueCanonicalizer {

    /// Built-in synonyms keyed by normalized form, so cross-script variants
    /// ("Seoul" ↔ "서울") and common KO/EN terms collapse together.
    private static let dictionary: [String: String] = [
        "seoul": "서울", "서울": "서울", "서울특별시": "서울", "서울시": "서울",
        "busan": "부산", "부산": "부산", "부산광역시": "부산",
        "incheon": "인천", "인천": "인천", "인천광역시": "인천",
        "daegu": "대구", "대구": "대구", "daejeon": "대전", "대전": "대전",
        "gwangju": "광주", "광주": "광주", "ulsan": "울산", "울산": "울산",
        "sejong": "세종", "세종": "세종",
        "gyeonggi": "경기", "경기": "경기", "경기도": "경기",
        "pohang": "포항", "포항": "포항", "포항시": "포항",
        "jeju": "제주", "제주": "제주", "제주도": "제주",
        "southkorea": "대한민국", "korea": "대한민국", "republicofkorea": "대한민국",
        "한국": "대한민국", "대한민국": "대한민국", "남한": "대한민국",
        // 최종본 기준 영문 표기
        "male": "Male", "m": "Male", "남": "Male", "남자": "Male", "남성": "Male",
        "female": "Female", "f": "Female", "여": "Female", "여자": "Female", "여성": "Female",
        "yes": "예", "y": "예", "예": "예", "네": "예", "true": "예",
        "no": "아니오", "n": "아니오", "아니오": "아니오", "아니요": "아니오", "false": "아니오"
    ]

    /// Normalized matching key: lowercased, non-alphanumerics stripped (Hangul kept).
    static func key(_ s: String) -> String {
        String(String.UnicodeScalarView(
            s.lowercased().unicodeScalars.filter { CharacterSet.alphanumerics.contains($0) }
        ))
    }

    /// 내장 사전이 아는 값이면 그 표준형을 돌려준다 (서울특별시→서울, seoul→서울).
    /// 유사도 추천에서 한↔영 다리 역할.
    static func canonical(_ s: String) -> String? { dictionary[key(s)] }

    /// Propose original → canonical for a column's values.
    /// A dictionary hit wins; otherwise variants sharing a normalized key collapse
    /// onto their most frequent spelling.
    static func suggest(_ values: [DistinctValue]) -> [String: String] {
        var representative: [String: DistinctValue] = [:]   // normalized key -> most frequent value
        for v in values {
            let k = key(v.value)
            if let cur = representative[k], cur.count >= v.count { continue }
            representative[k] = v
        }
        var out: [String: String] = [:]
        for v in values {
            let k = key(v.value)
            if let canon = dictionary[k] {
                out[v.value] = canon
            } else if let rep = representative[k] {
                out[v.value] = rep.value
            } else {
                out[v.value] = v.value
            }
        }
        return out
    }
}

// MARK: - Similarity (매핑 추천)

/// 값과 매핑표 통일 값 사이의 유사도. 매핑표 밖의 값에 가장 가까운 허용 값을
/// 추천하는 데 쓴다 — 추천은 제안일 뿐, 적용은 항상 사용자 승인으로만 된다.
enum Similarity {

    /// 0(다름)…1(같음). 정규화 키 비교 → 내장 사전 다리(서울↔Seoul) →
    /// 포함 관계 → 편집 거리 순으로 평가한다.
    static func score(_ a: String, _ b: String) -> Double {
        let ka = ValueCanonicalizer.key(a), kb = ValueCanonicalizer.key(b)
        if ka == kb && !ka.isEmpty { return 1 }
        // 사전 다리: 둘 다 아는 값이고 표준형이 같으면 사실상 동의어
        if let ca = ValueCanonicalizer.canonical(a), let cb = ValueCanonicalizer.canonical(b),
           ca == cb { return 0.95 }
        if ka.isEmpty || kb.isEmpty { return 0 }
        if ka.contains(kb) || kb.contains(ka) {
            let ratio = Double(min(ka.count, kb.count)) / Double(max(ka.count, kb.count))
            return 0.7 + 0.2 * ratio
        }
        let d = levenshtein(Array(ka), Array(kb))
        return max(0, 1 - Double(d) / Double(max(ka.count, kb.count)))
    }

    /// 후보 중 가장 유사한 값. 임계값(기본 0.5) 미만이면 추천하지 않는다.
    static func best(_ value: String, in candidates: [String],
                     minScore: Double = 0.5) -> (target: String, score: Double)? {
        let scored = candidates.map { ($0, score(value, $0)) }
        guard let top = scored.max(by: { $0.1 < $1.1 }), top.1 >= minScore else { return nil }
        return (top.0, top.1)
    }

    private static func levenshtein(_ a: [Character], _ b: [Character]) -> Int {
        if a.isEmpty { return b.count }
        if b.isEmpty { return a.count }
        var prev = Array(0...b.count)
        var cur = [Int](repeating: 0, count: b.count + 1)
        for i in 1...a.count {
            cur[0] = i
            for j in 1...b.count {
                cur[j] = min(prev[j] + 1, cur[j-1] + 1,
                             prev[j-1] + (a[i-1] == b[j-1] ? 0 : 1))
            }
            swap(&prev, &cur)
        }
        return prev[b.count]
    }
}

// MARK: - Mapping table import

/// Parses a user-supplied mapping table (pasted text or a loaded CSV/TSV) into
/// `원본 → 통일` pairs. Each line is one rule: the original value, a delimiter,
/// then the value it should become. Accepts tab, `→`, `=>`, `->`, `:` or comma
/// as the delimiter (whichever appears first), so most spreadsheet copies and
/// hand-typed lists parse without reformatting.
enum MappingTableParser {

    struct Pair: Identifiable {
        var id: String { from }
        let from: String
        let to: String
    }

    /// Result of parsing: valid pairs plus the line numbers we couldn't read.
    struct Parsed {
        var pairs: [Pair]
        var skipped: [Int]      // 1-based line numbers with no delimiter
    }

    /// Delimiters tried in order; the earliest one found in a line wins.
    private static let delimiters = ["\t", "→", "=>", "->", ":", ","]

    static func parse(_ text: String) -> Parsed {
        var pairs: [Pair] = []
        var seen = Set<String>()
        var skipped: [Int] = []
        let lines = text.components(separatedBy: .newlines)
        for (i, rawLine) in lines.enumerated() {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            if line.isEmpty { continue }
            guard let (from, to) = split(line) else { skipped.append(i + 1); continue }
            // 통일 값이 비면 원본을 빈 값으로 지워버리므로 ‘못 읽은 줄’로 취급.
            if to.isEmpty { skipped.append(i + 1); continue }
            if from.isEmpty || seen.contains(from) { continue }
            seen.insert(from)
            pairs.append(Pair(from: from, to: to))
        }
        return Parsed(pairs: pairs, skipped: skipped)
    }

    /// Split a line on its first delimiter into (from, to), trimmed.
    private static func split(_ line: String) -> (String, String)? {
        let hit = delimiters
            .compactMap { d in line.range(of: d).map { (range: $0, delim: d) } }
            .min { $0.range.lowerBound < $1.range.lowerBound }
        guard let hit else { return nil }
        let from = String(line[..<hit.range.lowerBound]).trimmingCharacters(in: .whitespaces)
        let to = String(line[hit.range.upperBound...]).trimmingCharacters(in: .whitespaces)
        return (from, to)
    }
}

// MARK: - Regex cleanup presets

/// One reusable find-and-replace rule the user can toggle on for a column.
/// `pattern` is an ICU regular expression; matches are replaced with `replacement`.
struct RegexPreset: Identifiable, Hashable {
    let id: String
    let name: String
    let summary: String
    let pattern: String
    let replacement: String
    let example: String     // "원본 → 결과", for the picker
}

/// A menu of regexes that come up constantly in data cleaning. The user picks
/// which to apply to a column (optionally adding their own), previews the
/// result, then commits — the cleaned values flow through the merge's valueMap.
enum RegexLibrary {

    static let presets: [RegexPreset] = [
        RegexPreset(id: "trim", name: "앞뒤 공백 제거",
                    summary: "값 양 끝의 공백을 없앱니다.",
                    pattern: "^\\s+|\\s+$", replacement: "",
                    example: "‘ 김지호 ’ → ‘김지호’"),
        RegexPreset(id: "collapse", name: "연속 공백 → 한 칸",
                    summary: "여러 칸 띄어쓰기를 한 칸으로 줄입니다.",
                    pattern: "\\s{2,}", replacement: " ",
                    example: "‘김  지호’ → ‘김 지호’"),
        RegexPreset(id: "nospace", name: "모든 공백 제거",
                    summary: "값 안의 모든 띄어쓰기를 없앱니다.",
                    pattern: "\\s+", replacement: "",
                    example: "‘김 지 호’ → ‘김지호’"),
        RegexPreset(id: "parens", name: "괄호와 안의 내용 제거",
                    summary: "(), [], {} 안의 병기를 지웁니다.",
                    pattern: "\\s*[\\(\\[\\{（【][^\\)\\]\\}）】]*[\\)\\]\\}）】]", replacement: "",
                    example: "‘김지호(Kim)’ → ‘김지호’"),
        RegexPreset(id: "special", name: "특수문자 제거",
                    summary: "한글·영문·숫자·공백만 남깁니다.",
                    pattern: "[^0-9A-Za-z가-힣\\s]", replacement: "",
                    example: "‘김*지호!’ → ‘김지호’"),
        RegexPreset(id: "nodigit", name: "숫자 제거",
                    summary: "값에 섞인 숫자를 모두 지웁니다.",
                    pattern: "[0-9]", replacement: "",
                    example: "‘김지호1’ → ‘김지호’"),
        RegexPreset(id: "digitonly", name: "숫자만 남기기",
                    summary: "숫자가 아닌 문자를 모두 지웁니다.",
                    pattern: "[^0-9]", replacement: "",
                    example: "‘010-1234’ → ‘0101234’"),
        RegexPreset(id: "hangulonly", name: "한글만 남기기",
                    summary: "한글과 공백만 남기고 나머지를 지웁니다.",
                    pattern: "[^가-힣\\s]", replacement: "",
                    example: "‘김지호Kim’ → ‘김지호’"),
        RegexPreset(id: "jamo", name: "낱자(ㅋㅋ·ㅎㅎ) 제거",
                    summary: "홀로 쓰인 자음·모음을 지웁니다.",
                    pattern: "[ㄱ-ㅎㅏ-ㅣ]+", replacement: "",
                    example: "‘김지호ㅋㅋ’ → ‘김지호’"),
        RegexPreset(id: "html", name: "HTML 태그 제거",
                    summary: "<b>…</b> 같은 태그를 지웁니다.",
                    pattern: "<[^>]+>", replacement: "",
                    example: "‘<b>김</b>’ → ‘김’"),
        RegexPreset(id: "emoji", name: "이모지 제거",
                    summary: "그림 이모지를 지웁니다.",
                    pattern: "[\\x{1F000}-\\x{1FAFF}\\x{2600}-\\x{27BF}\\x{FE0F}\\x{2190}-\\x{21FF}]",
                    replacement: "",
                    example: "‘김지호😀’ → ‘김지호’"),
        RegexPreset(id: "invisible", name: "보이지 않는 문자 제거",
                    summary: "제로폭 공백 등 숨은 문자를 지웁니다.",
                    pattern: "[\\x{200B}-\\x{200D}\\x{FEFF}\\x{00AD}]", replacement: "",
                    example: "‘김\u{200B}지호’ → ‘김지호’")
    ]
}

/// Applies an ordered list of regex presets to a value, in sequence.
enum RegexCleaner {

    /// Is this a valid ICU regular expression?
    static func isValid(_ pattern: String) -> Bool {
        (try? NSRegularExpression(pattern: pattern)) != nil
    }

    /// Does the whole string match the pattern (anchored start-to-end)?
    /// An invalid pattern returns true so a half-typed regex doesn't flag
    /// every value as a failure while the user is still typing it.
    static func fullyMatches(_ s: String, _ pattern: String) -> Bool {
        guard !pattern.isEmpty, let re = try? NSRegularExpression(pattern: pattern) else { return true }
        let range = NSRange(s.startIndex..., in: s)
        return re.firstMatch(in: s, range: range)?.range == range
    }

    /// Run each preset's find-and-replace over `value`, in order. Invalid
    /// patterns are skipped so one bad rule can't break the rest.
    static func apply(_ presets: [RegexPreset], to value: String) -> String {
        var v = value
        for p in presets where isValid(p.pattern) {
            v = v.replacingOccurrences(of: p.pattern, with: p.replacement,
                                       options: .regularExpression)
        }
        return v
    }
}
