import Foundation

/// One distinct value found in a merged column, with how many rows carry it.
struct DistinctValue: Identifiable {
    var id: String { value }
    let value: String
    let count: Int
}

/// Discovers which merged columns hold categorical values worth unifying
/// (e.g. a 도시 column where some rows say "Seoul" and others "서울"),
/// and the distinct values that land in each across all files.
enum ValueScanner {

    /// Free-text or derived columns — never offered for value unification.
    static let freeText: Set<UnifiedColumn> = [
        .koreanName, .email, .phone, .phoneClean, .dob, .dobClean, .code, .channel, .dupFlag,
        .currentAddress, .selfIntro, .motivation, .essayInitiative, .essayCraft, .essayChallenge,
        .portfolioLinks, .portfolioFile, .cvFile, .coreCompetencies, .submittedAt,
        .major, .school, .schoolCompany, .majorDept, .snsChannel
    ]

    /// A column with more distinct values than this is treated as free-text, not categorical.
    static let maxDistinct = 40

    /// The mapped (un-normalized) value of a unified column for one source row.
    private static func value(_ col: UnifiedColumn, row: [String: String], plan: FilePlan) -> String {
        guard let src = plan.mapping[col], !src.isEmpty else { return "" }
        return (row[src] ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Distinct non-empty values for a column across all files, most frequent first.
    static func distinct(_ col: UnifiedColumn, in plans: [FilePlan]) -> [DistinctValue] {
        var counts: [String: Int] = [:]
        for plan in plans where !(plan.mapping[col] ?? "").isEmpty {
            for row in plan.rows {
                let v = value(col, row: row, plan: plan)
                if v.isEmpty { continue }
                counts[v, default: 0] += 1
            }
        }
        return counts
            .sorted { $0.value != $1.value ? $0.value > $1.value : $0.key < $1.key }
            .map { DistinctValue(value: $0.key, count: $0.value) }
    }

    /// Columns worth a value-unification pass: mapped somewhere, categorical, low-cardinality.
    static func candidates(in plans: [FilePlan]) -> [UnifiedColumn] {
        UnifiedColumn.allCases.filter { col in
            guard !freeText.contains(col) else { return false }
            guard plans.contains(where: { !($0.mapping[col] ?? "").isEmpty }) else { return false }
            let n = distinct(col, in: plans).count
            return n >= 2 && n <= maxDistinct
        }
    }
}

// MARK: - Column-centric review

/// How a final column should be reviewed.
/// - category: distinct values to unify
/// - phone/date: auto-normalized, shown as original → cleaned samples
/// - freeText: kept as-is, shown as a few sample values
/// - derived: generated by the merge (channel, dup flag, *(Clean) columns)
enum ColumnReviewKind { case category, phone, date, freeText, derived }

/// One original → normalized example shown when reviewing a column.
struct ColumnExample: Identifiable {
    let id = UUID()
    let original: String
    let cleaned: String
    let flagged: Bool          // non-standard phone / unparseable date
}

/// What to review for a single final output column.
struct ColumnReview: Identifiable {
    var id: String { column.rawValue }
    let column: UnifiedColumn
    let kind: ColumnReviewKind
    var values: [DistinctValue] = []     // categorical: distinct values to unify
    var examples: [ColumnExample] = []   // phone/date: original → normalized samples
    var samples: [String] = []           // freeText: a few sample values
    var note: String = ""                // derived/freeText: short description
    var flaggedCount: Int = 0            // phone/date: rows needing attention
    var distinctCount: Int = 0
    var total: Int = 0                   // rows carrying a value
}

/// Builds the column-centric review: which columns the merge will produce,
/// and, per column, the values or formats the user should look over.
enum ColumnReviewBuilder {

    static func mappedSomewhere(_ col: UnifiedColumn, in plans: [FilePlan]) -> Bool {
        plans.contains { !($0.mapping[col] ?? "").isEmpty }
    }

    /// Every non-empty mapped value of a column across all files.
    static func rawValues(_ col: UnifiedColumn, in plans: [FilePlan]) -> [String] {
        var out: [String] = []
        for plan in plans {
            guard let src = plan.mapping[col], !src.isEmpty else { continue }
            for row in plan.rows {
                let v = (row[src] ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
                if !v.isEmpty { out.append(v) }
            }
        }
        return out
    }

    /// Columns that will appear in the merged file, in export order.
    static func finalColumns(in plans: [FilePlan]) -> [UnifiedColumn] {
        UnifiedColumn.allCases.filter { col in
            switch col {
            case .channel, .dupFlag: return true
            case .phoneClean: return mappedSomewhere(.phone, in: plans)
            case .dobClean:   return mappedSomewhere(.dob, in: plans)
            default:          return mappedSomewhere(col, in: plans)
            }
        }
    }

    private static let isoDate = "^\\d{4}-\\d{2}-\\d{2}$"

    /// One review per final column, in export order.
    static func reviews(in plans: [FilePlan]) -> [ColumnReview] {
        let categorical = Set(ValueScanner.candidates(in: plans))
        let rowTotal = plans.reduce(0) { $0 + $1.rows.count }

        return finalColumns(in: plans).map { col in
            switch col {
            case .channel:
                return ColumnReview(column: col, kind: .derived,
                                    note: "각 행이 어느 파일(간편지원/일반지원)에서 왔는지 자동으로 채워집니다.",
                                    total: rowTotal)
            case .dupFlag:
                return ColumnReview(column: col, kind: .derived,
                                    note: "전화번호 기준 중복 검사 결과(유지/삭제)가 자동으로 채워집니다.",
                                    total: rowTotal)
            case .phoneClean:
                return ColumnReview(column: col, kind: .derived,
                                    note: "‘Phone Number’에서 ‘010-XXXX-XXXX’ 형태로 자동 생성됩니다.")
            case .dobClean:
                return ColumnReview(column: col, kind: .derived,
                                    note: "‘Date of Birth’에서 ‘yyyy-MM-dd’ 형태로 자동 생성됩니다.")
            case .phone:
                let raw = rawValues(.phone, in: plans)
                let flagged = Set(raw.filter { !Normalizer.cleanPhone($0).hasPrefix("010-") })
                return ColumnReview(column: col, kind: .phone,
                                    examples: examples(raw, flaggedKeys: flagged, clean: Normalizer.cleanPhone),
                                    note: "원본은 그대로 저장되고, ‘전화번호(Clean)’ 컬럼에 정규화본이 함께 생성됩니다.",
                                    flaggedCount: flagged.count,
                                    distinctCount: Set(raw).count, total: raw.count)
            case .dob:
                let raw = rawValues(.dob, in: plans)
                let flagged = Set(raw.filter {
                    Normalizer.cleanDate($0) == $0
                        && $0.range(of: isoDate, options: .regularExpression) == nil
                })
                return ColumnReview(column: col, kind: .date,
                                    examples: examples(raw, flaggedKeys: flagged, clean: Normalizer.cleanDate),
                                    note: "원본은 그대로 저장되고, ‘생년월일(Clean)’ 컬럼에 정규화본이 함께 생성됩니다.",
                                    flaggedCount: flagged.count,
                                    distinctCount: Set(raw).count, total: raw.count)
            default:
                if categorical.contains(col) {
                    let vals = ValueScanner.distinct(col, in: plans)
                    return ColumnReview(column: col, kind: .category, values: vals,
                                        distinctCount: vals.count,
                                        total: vals.reduce(0) { $0 + $1.count })
                } else {
                    let d = ValueScanner.distinct(col, in: plans)
                    return ColumnReview(column: col, kind: .freeText,
                                        samples: d.prefix(5).map { $0.value },
                                        note: "자유 입력 값이라 통일 없이 원본 그대로 저장됩니다.",
                                        distinctCount: d.count,
                                        total: d.reduce(0) { $0 + $1.count })
                }
            }
        }
    }

    /// Up to 8 distinct examples, flagged ones first.
    private static func examples(_ raw: [String], flaggedKeys: Set<String>,
                                 clean: (String) -> String) -> [ColumnExample] {
        var seen = Set<String>()
        var out: [ColumnExample] = []
        let ordered = raw.filter { flaggedKeys.contains($0) } + raw
        for v in ordered where !seen.contains(v) {
            seen.insert(v)
            out.append(ColumnExample(original: v, cleaned: clean(v), flagged: flaggedKeys.contains(v)))
            if out.count >= 8 { break }
        }
        return out
    }
}

/// Suggests how to collapse value variants onto one canonical form.
enum ValueCanonicalizer {

    /// Built-in synonyms keyed by normalized form, so cross-script variants
    /// ("Seoul" ↔ "서울") and common KO/EN terms collapse together.
    private static let dictionary: [String: String] = [
        "seoul": "서울", "서울": "서울", "서울특별시": "서울", "서울시": "서울",
        "busan": "부산", "부산": "부산", "부산광역시": "부산",
        "incheon": "인천", "인천": "인천", "인천광역시": "인천",
        "daegu": "대구", "대구": "대구", "daejeon": "대전", "대전": "대전",
        "gwangju": "광주", "광주": "광주", "ulsan": "울산", "울산": "울산",
        "sejong": "세종", "세종": "세종",
        "gyeonggi": "경기", "경기": "경기", "경기도": "경기",
        "pohang": "포항", "포항": "포항", "포항시": "포항",
        "jeju": "제주", "제주": "제주", "제주도": "제주",
        "southkorea": "대한민국", "korea": "대한민국", "republicofkorea": "대한민국",
        "한국": "대한민국", "대한민국": "대한민국", "남한": "대한민국",
        "male": "남성", "m": "남성", "남": "남성", "남자": "남성", "남성": "남성",
        "female": "여성", "f": "여성", "여": "여성", "여자": "여성", "여성": "여성",
        "yes": "예", "y": "예", "예": "예", "네": "예", "true": "예",
        "no": "아니오", "n": "아니오", "아니오": "아니오", "아니요": "아니오", "false": "아니오"
    ]

    /// Normalized matching key: lowercased, non-alphanumerics stripped (Hangul kept).
    static func key(_ s: String) -> String {
        String(String.UnicodeScalarView(
            s.lowercased().unicodeScalars.filter { CharacterSet.alphanumerics.contains($0) }
        ))
    }

    /// Propose original → canonical for a column's values.
    /// A dictionary hit wins; otherwise variants sharing a normalized key collapse
    /// onto their most frequent spelling.
    static func suggest(_ values: [DistinctValue]) -> [String: String] {
        var representative: [String: DistinctValue] = [:]   // normalized key -> most frequent value
        for v in values {
            let k = key(v.value)
            if let cur = representative[k], cur.count >= v.count { continue }
            representative[k] = v
        }
        var out: [String: String] = [:]
        for v in values {
            let k = key(v.value)
            if let canon = dictionary[k] {
                out[v.value] = canon
            } else if let rep = representative[k] {
                out[v.value] = rep.value
            } else {
                out[v.value] = v.value
            }
        }
        return out
    }
}
